spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.hibernate.type: trace